#===================================================================================================
#
# swagger-spec-mgr server設定
#
#===================================================================================================
#---------------------------------------------------------------------------------------------------
# spec-mgr
#---------------------------------------------------------------------------------------------------
# server起動ポート
server:
  port: ${SERVER_PORT}
  contextPath: "${CONTEXTPATH}"

spec.mgr:
  # デフォルトコミット情報
  defaultCommitInfo:
    # ユーザ
    user: "${SCM_DEFAULT_USER}"
    # メッセージ
    message: "${SCM_DEFAULT_COMMIT_MESSAGE}"

  # ディレクトリ情報
  dirInfo:
    # 実行スクリプト
    bin: "${DIR_BIN}"
    # ファイル出力ルート
    data: "${DIR_DATA}"
    # 分割済み定義 ※gitリポジトリルートからの相対パス
    specs: "${RELDIR_SPECS}"

  # 分割除外パス正規表現リスト
  splitIgnoreRegexList:
  - "/info/.*"
  - "/tags/.*"
  - "/schemas/.*"
  - "/securityDefinitions/.*"
  - "/paths/.*/consumes"
  - "/paths/.*/parameters"
  - "/paths/.*/produces"
  - "/paths/.*/responses"
  - "/paths/.*/tags"
  - "/paths/.*/security"

  # CORS設定
  cors:
    allowOrigin: "*"
    allowMethods: "GET, POST, PUT, DELETE"
    allowHeaders: "Content-Type,X-Commit-User,X-Commit-Message"
    allowMaxAge: 864000

  # スクリプト実行時環境変数
  scriptEnv:
    LOG__RAW_OUTPUT: "true"
    SOME_VAR: "SOME_VALUE"


#---------------------------------------------------------------------------------------------------
# swagger
#---------------------------------------------------------------------------------------------------
springfox.documentation.swagger.v2.path: "/api-docs"

spring.jackson.date-format: "io.swagger.RFC3339DateFormat"
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false
