#===================================================================================================
#
# swagger-spec-mgr server設定
#
#===================================================================================================
#---------------------------------------------------------------------------------------------------
# spec-mgr
#---------------------------------------------------------------------------------------------------
# server起動ポート
server:
  port: ${SERVER_PORT}
  contextPath: "/v1"

spec.mgr:
  # デフォルトcommitユーザ
  defaultScmUser: "${SCM_DEFAULT_USER}"
  # ファイル出力ルートディレクトリ相対パス
  dirData: "${DIR_DATA}"
  # 分割済み定義ファイル出力ディレクトリ相対パス
  relDirSpecs: "${RELDIR_SPECS}"
  # 分割除外パス正規表現リスト
  splitIgnoreRegexs:
  - "/info/.*"
  - "/tags/.*"
  - "/schemas/.*"
  - "/securityDefinitions/.*"
  - "/paths/.*/consumes"
  - "/paths/.*/parameters"
  - "/paths/.*/produces"
  - "/paths/.*/responses"
  - "/paths/.*/tags"
  - "/paths/.*/security"


#---------------------------------------------------------------------------------------------------
# swagger
#---------------------------------------------------------------------------------------------------
springfox.documentation.swagger.v2.path: "/api-docs"

spring.jackson.date-format: "io.swagger.RFC3339DateFormat"
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false
